---

- name: Create Root NFS Directory
  ansible.builtin.file:
    path: "{{ nfs_server_root_directory }}"
    state: directory
    owner: "{{ nfs_server_root_directory_owner }}"
    group: "{{ nfs_server_root_directory_group }}"
    mode: "{{ nfs_server_root_directory_mode }}"

- name: Configure Exports file
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
  notify:
    - Restart NFS Server

...
